// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_alarmroom
global.__objectDepths[1] = -10; // obj_enemydeath
global.__objectDepths[2] = 0; // obj_leveltrack_cutscene
global.__objectDepths[3] = 0; // obj_level1track
global.__objectDepths[4] = 0; // obj_gameover
global.__objectDepths[5] = 0; // obj_spawn
global.__objectDepths[6] = 0; // obj_insertcoinstart
global.__objectDepths[7] = 0; // obj_f4
global.__objectDepths[8] = 0; // obj_fullscreen
global.__objectDepths[9] = 0; // obj_scene3
global.__objectDepths[10] = 0; // obj_scene4
global.__objectDepths[11] = 0; // obj_soundcontroller
global.__objectDepths[12] = 0; // obj_scene2
global.__objectDepths[13] = 0; // obj_continue
global.__objectDepths[14] = 0; // obj_insertcoin
global.__objectDepths[15] = -1000; // obj_score
global.__objectDepths[16] = 0; // obj_scene1
global.__objectDepths[17] = 0; // obj_playertut3
global.__objectDepths[18] = 0; // obj_title
global.__objectDepths[19] = 0; // obj_scene0
global.__objectDepths[20] = 0; // obj_plot1
global.__objectDepths[21] = 0; // obj_plot2
global.__objectDepths[22] = 0; // obj_tutorial
global.__objectDepths[23] = 0; // obj_plot3
global.__objectDepths[24] = -1000; // obj_lives
global.__objectDepths[25] = 0; // obj_playertut1
global.__objectDepths[26] = 0; // obj_playertut2
global.__objectDepths[27] = 0; // obj_plot4
global.__objectDepths[28] = -1; // obj_playerdeath
global.__objectDepths[29] = 0; // obj_hitbox
global.__objectDepths[30] = 0; // obj_mokey3_enemy2
global.__objectDepths[31] = 0; // obj_monkey1_enemy
global.__objectDepths[32] = -3; // obj_boss_samurai
global.__objectDepths[33] = 0; // obj_frogboss_hitbox
global.__objectDepths[34] = 0; // obj_samurai_hitbox
global.__objectDepths[35] = 0; // obj_frog_hitbox
global.__objectDepths[36] = -3; // obj_frog_boss
global.__objectDepths[37] = 0; // obj_dragon_hitbox
global.__objectDepths[38] = 0; // obj_bullet_samurai
global.__objectDepths[39] = 0; // obj_attack_hitbox
global.__objectDepths[40] = -3; // obj_boss_dragon
global.__objectDepths[41] = -2; // obj_player
global.__objectDepths[42] = -3; // obj_frog2
global.__objectDepths[43] = 0; // obj_monkey3_enemy
global.__objectDepths[44] = 0; // obj_monkey2_enemy
global.__objectDepths[45] = 0; // obj_monkey_small
global.__objectDepths[46] = -2; // obj_spike
global.__objectDepths[47] = 0; // obj_attack_hitbox2
global.__objectDepths[48] = 0; // obj_frog
global.__objectDepths[49] = 0; // obj_enemy_boss
global.__objectDepths[50] = 0; // obj_projectile
global.__objectDepths[51] = -3; // obj_dragon_fire
global.__objectDepths[52] = -20; // obj_level2
global.__objectDepths[53] = 0; // obj_boss_teleporter1
global.__objectDepths[54] = 0; // obj_bullet
global.__objectDepths[55] = 0; // obj_bullet2
global.__objectDepths[56] = -1; // obj_enemy_obstacle
global.__objectDepths[57] = -2; // obj_hole
global.__objectDepths[58] = 0; // obj_teleporter
global.__objectDepths[59] = 0; // obj_wall
global.__objectDepths[60] = 0; // obj_plat
global.__objectDepths[61] = -10; // obj_roof_left_end
global.__objectDepths[62] = -2; // obj_roof_middle
global.__objectDepths[63] = -20; // obj_level3
global.__objectDepths[64] = -3; // obj_frog_bullet
global.__objectDepths[65] = -1; // obj_enemy
global.__objectDepths[66] = -10; // obj_roof_right_end
global.__objectDepths[67] = -5; // obj_sliding_door_bottom
global.__objectDepths[68] = -5; // obj_sliding_door_middle
global.__objectDepths[69] = -5; // obj_sliding_door_top
global.__objectDepths[70] = 0; // obj_plat_left
global.__objectDepths[71] = 0; // obj_plat_mid
global.__objectDepths[72] = -1; // obj_castle_floor_left
global.__objectDepths[73] = 0; // obj_underground
global.__objectDepths[74] = 0; // obj_plat_right
global.__objectDepths[75] = 0; // obj_platform
global.__objectDepths[76] = -1; // obj_castle_floor_left_under
global.__objectDepths[77] = -20; // obj_castle_floor_middle
global.__objectDepths[78] = -5; // obj_rock_flat
global.__objectDepths[79] = 0; // obj_underground_bottom
global.__objectDepths[80] = 0; // obj_underground_top
global.__objectDepths[81] = -1; // obj_castle_floor_under
global.__objectDepths[82] = -1; // obj_castle_floor_right
global.__objectDepths[83] = -1; // obj_castle_floor_right_under
global.__objectDepths[84] = 0; // obj_wall6
global.__objectDepths[85] = 0; // obj_dirt_right
global.__objectDepths[86] = 0; // obj_wall1
global.__objectDepths[87] = 0; // obj_wall3
global.__objectDepths[88] = -5; // obj_rock_bottom
global.__objectDepths[89] = 0; // obj_wall5
global.__objectDepths[90] = -5; // obj_rock_top
global.__objectDepths[91] = 0; // obj_dirt1
global.__objectDepths[92] = 0; // obj_dirt_dark1
global.__objectDepths[93] = 0; // obj_dirt_left
global.__objectDepths[94] = 0; // obj_dirt_middle
global.__objectDepths[95] = -1; // obj_tree_branch3
global.__objectDepths[96] = 0; // obj_bamboo_only
global.__objectDepths[97] = 0; // obj_bamboo_rocks
global.__objectDepths[98] = 0; // obj_grass
global.__objectDepths[99] = 0; // obj_grass_flower
global.__objectDepths[100] = 0; // obj_trunk
global.__objectDepths[101] = 0; // obj_wall4
global.__objectDepths[102] = 0; // obj_tree_branch2
global.__objectDepths[103] = 0; // obj_tree_body
global.__objectDepths[104] = -1; // obj_tree_branch1
global.__objectDepths[105] = 0; // obj_wall2


global.__objectNames[0] = "obj_alarmroom";
global.__objectNames[1] = "obj_enemydeath";
global.__objectNames[2] = "obj_leveltrack_cutscene";
global.__objectNames[3] = "obj_level1track";
global.__objectNames[4] = "obj_gameover";
global.__objectNames[5] = "obj_spawn";
global.__objectNames[6] = "obj_insertcoinstart";
global.__objectNames[7] = "obj_f4";
global.__objectNames[8] = "obj_fullscreen";
global.__objectNames[9] = "obj_scene3";
global.__objectNames[10] = "obj_scene4";
global.__objectNames[11] = "obj_soundcontroller";
global.__objectNames[12] = "obj_scene2";
global.__objectNames[13] = "obj_continue";
global.__objectNames[14] = "obj_insertcoin";
global.__objectNames[15] = "obj_score";
global.__objectNames[16] = "obj_scene1";
global.__objectNames[17] = "obj_playertut3";
global.__objectNames[18] = "obj_title";
global.__objectNames[19] = "obj_scene0";
global.__objectNames[20] = "obj_plot1";
global.__objectNames[21] = "obj_plot2";
global.__objectNames[22] = "obj_tutorial";
global.__objectNames[23] = "obj_plot3";
global.__objectNames[24] = "obj_lives";
global.__objectNames[25] = "obj_playertut1";
global.__objectNames[26] = "obj_playertut2";
global.__objectNames[27] = "obj_plot4";
global.__objectNames[28] = "obj_playerdeath";
global.__objectNames[29] = "obj_hitbox";
global.__objectNames[30] = "obj_mokey3_enemy2";
global.__objectNames[31] = "obj_monkey1_enemy";
global.__objectNames[32] = "obj_boss_samurai";
global.__objectNames[33] = "obj_frogboss_hitbox";
global.__objectNames[34] = "obj_samurai_hitbox";
global.__objectNames[35] = "obj_frog_hitbox";
global.__objectNames[36] = "obj_frog_boss";
global.__objectNames[37] = "obj_dragon_hitbox";
global.__objectNames[38] = "obj_bullet_samurai";
global.__objectNames[39] = "obj_attack_hitbox";
global.__objectNames[40] = "obj_boss_dragon";
global.__objectNames[41] = "obj_player";
global.__objectNames[42] = "obj_frog2";
global.__objectNames[43] = "obj_monkey3_enemy";
global.__objectNames[44] = "obj_monkey2_enemy";
global.__objectNames[45] = "obj_monkey_small";
global.__objectNames[46] = "obj_spike";
global.__objectNames[47] = "obj_attack_hitbox2";
global.__objectNames[48] = "obj_frog";
global.__objectNames[49] = "obj_enemy_boss";
global.__objectNames[50] = "obj_projectile";
global.__objectNames[51] = "obj_dragon_fire";
global.__objectNames[52] = "obj_level2";
global.__objectNames[53] = "obj_boss_teleporter1";
global.__objectNames[54] = "obj_bullet";
global.__objectNames[55] = "obj_bullet2";
global.__objectNames[56] = "obj_enemy_obstacle";
global.__objectNames[57] = "obj_hole";
global.__objectNames[58] = "obj_teleporter";
global.__objectNames[59] = "obj_wall";
global.__objectNames[60] = "obj_plat";
global.__objectNames[61] = "obj_roof_left_end";
global.__objectNames[62] = "obj_roof_middle";
global.__objectNames[63] = "obj_level3";
global.__objectNames[64] = "obj_frog_bullet";
global.__objectNames[65] = "obj_enemy";
global.__objectNames[66] = "obj_roof_right_end";
global.__objectNames[67] = "obj_sliding_door_bottom";
global.__objectNames[68] = "obj_sliding_door_middle";
global.__objectNames[69] = "obj_sliding_door_top";
global.__objectNames[70] = "obj_plat_left";
global.__objectNames[71] = "obj_plat_mid";
global.__objectNames[72] = "obj_castle_floor_left";
global.__objectNames[73] = "obj_underground";
global.__objectNames[74] = "obj_plat_right";
global.__objectNames[75] = "obj_platform";
global.__objectNames[76] = "obj_castle_floor_left_under";
global.__objectNames[77] = "obj_castle_floor_middle";
global.__objectNames[78] = "obj_rock_flat";
global.__objectNames[79] = "obj_underground_bottom";
global.__objectNames[80] = "obj_underground_top";
global.__objectNames[81] = "obj_castle_floor_under";
global.__objectNames[82] = "obj_castle_floor_right";
global.__objectNames[83] = "obj_castle_floor_right_under";
global.__objectNames[84] = "obj_wall6";
global.__objectNames[85] = "obj_dirt_right";
global.__objectNames[86] = "obj_wall1";
global.__objectNames[87] = "obj_wall3";
global.__objectNames[88] = "obj_rock_bottom";
global.__objectNames[89] = "obj_wall5";
global.__objectNames[90] = "obj_rock_top";
global.__objectNames[91] = "obj_dirt1";
global.__objectNames[92] = "obj_dirt_dark1";
global.__objectNames[93] = "obj_dirt_left";
global.__objectNames[94] = "obj_dirt_middle";
global.__objectNames[95] = "obj_tree_branch3";
global.__objectNames[96] = "obj_bamboo_only";
global.__objectNames[97] = "obj_bamboo_rocks";
global.__objectNames[98] = "obj_grass";
global.__objectNames[99] = "obj_grass_flower";
global.__objectNames[100] = "obj_trunk";
global.__objectNames[101] = "obj_wall4";
global.__objectNames[102] = "obj_tree_branch2";
global.__objectNames[103] = "obj_tree_body";
global.__objectNames[104] = "obj_tree_branch1";
global.__objectNames[105] = "obj_wall2";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for